### ISSUE TITLE
Add the library to vcpkg

### ISSUE THREAD

**Issue by daljit97** [BowenFu/matchit.cpp#78]
**Describe the solution you'd like**
I would like to see this library added as a package for vcpkg.

**Describe alternatives you've considered**
Adding a header file is extremely convenient, but adding the package to vcpkg would provide automatic fixes and features for users.

**Additional context**
Since the library uses CMake already, I think the packaging for vcpkg shouldn't be difficult.

Thanks for the great effort!

**Comment by BowenFu** [comment]
@daljit97 Thanks for bringing this up. Will look into this later today. And if you are interested, can you help create a PR for it?

**Comment by daljit97** [comment]
Sure, I think I can give it a go.

**Comment by daljit97** [comment]
@BowenFu Created a draft pull request here https://github.com/microsoft/vcpkg/pull/26499. It doesn't seem to work as vcpkg fails to install the library (`ninja: error: unknown target 'install'`), but maybe you can figure why this is (I might have a look at this later time permitting).

**Comment by BowenFu** [comment]
Thanks. Will look into this later.

**Comment by BowenFu** [comment]
Looks like this cmd is failing.

cmake --build . --config Debug --target install -- -v -j12

Will try repro locally.

**Comment by daljit97** [comment]
@BowenFu Are you happy with the package name and description or anything else? If yes, I think I can submit the drafted pull request for review.

**Comment by BowenFu** [comment]
@daljit97 Sure. I see no problem with them. Feel free to submit. Thanks for your efforts.

**Comment by daljit97** [comment]
Alright, the pull request has been merged. If you want, you can mention that the library is available on vpckg in the installation section of the readme, so users will be aware of it.

**Comment by BowenFu** [comment]
Sure. I've updated the README to reflect that.
