### ISSUE TITLE
Add the library to conan

### ISSUE THREAD

**Issue by sanblch** [BowenFu/matchit.cpp#82]
As a conan user I wanted to have this library awailable via [conan-center-index](https://github.com/conan-io/conan-center-index). So I made a [PR](https://github.com/conan-io/conan-center-index/pull/12710) in there.

**Comment by BowenFu** [comment]
@sanblch Thanks for adding this! Will update the installation part after the PR gets committed.

**Comment by e-dant** [comment]
Using `project_options` will do this, and other things, easily. 

Something like this will work:

```

FetchContent_Declare(
  _project_options 
  URL "https://github.com/aminya/project_options/archive/refs/tags/v0.24.0.zip"
  DOWNLOAD_EXTRACT_TIMESTAMP
)

FetchContent_MakeAvailable(_project_options)

include("${_project_options_SOURCE_DIR}/Index.cmake")
include("${_project_options_SOURCE_DIR}/src/DynamicProjectOptions.cmake")

# run_vcpkg() should be called before defining project()
run_vcpkg()

# define things you want for your library here, such as Conan support, sanitizer builds, or packaging. 
project_options(
  ENABLE_CONAN
  # ...
)
```

**Comment by e-dant** [comment]
Oops -- I misread. This won't put it in the conan center. 

Still might be worthwhile for an easier CMake experience, though.

**Comment by BowenFu** [comment]
@sanblch @e-dant Thank you both for supporting this project.

@sanblch should we close this issue since the task is done?
