### ISSUE TITLE
Suggest adding three trivial overloads for a more uniform use of expr()

### ISSUE THREAD

**Issue by hugoetchegoyen** [BowenFu/matchit.cpp#94]
[matchit.txt](https://github.com/BowenFu/matchit.cpp/files/9965752/matchit.txt)

**Comment by BowenFu** [comment]
Hi @hugoetchegoyen, thanks for bringing this up and that is a very good topic.

"expr" was introduced one year ago and now we have a chance to rethink about it.
Maybe there is a chance to remove all its usage and provide overloaded versions for 
nullary callable, Id, and others for "when" and "operator=".

Then the sample would be like

```c++
#include "matchit.h"

template<typename T1, typename T2>
constexpr auto eval(std::tuple<char, T1, T2> const& exp)
{
    using namespace matchit;
    Id<T1> i;
    Id<T2> j;
    return match(exp)
    (
        pattern | ds('+', i, j) = i + j,
        pattern | ds('-', i, j) = i - j,
        pattern | ds('*', i, j) | when(i) = i, // previously not allowed
        pattern | ds('/', i, j) = 12345,        // previously not allowed
        pattern | _ = []
        {
            assert(false);
            return -1;
        }
    );
}
```

The only concern is about `others`. Would that be too risky if users provide a unary instead of nullary mistakenly and we silent the error and return the unary function as the result?

A compromise may be to keep expr for `others` only and deprecate its usage for `Id`.

What do you think?

Thanks,
Bowen

**Comment by hugoetchegoyen** [comment]
Hi Bowen,

Thanks for your reply.

I like the idea of eliminating the need to use expr() entirely by
overloading operator= and when() for nullary callables, Ids and others.

I realize that if the user mistakenly uses a unary instead of a nullary,
the unary will fall in the category of others and will be used as a plain
value, not called. I don't think this deserves a special protection.

I would not deprecate expr() but keep it around as an option, this way you
don´t break backward compatibility.

In some cases you might also like to use expr() for cosmetic reasons. For
example, consider a handler that returns a nullary lambda:

    pattern | _ =  []{ return []{ return 123; }; }

In my opinion it looks nicer with expr():

    pattern | _ =  expr([]{ return 123; })

Best regards,
Hugo

**Comment by hugoetchegoyen** [comment]
PS:

With my three trivial overloads the situation is like your second alternative: expr() is compulsory for others only. But it is not deprecated, on the contrary, it is generalized to accept everything.

**Comment by BowenFu** [comment]
@hugoetchegoyen good pointer about "this doesn't deserve a special protection". And by deprecate I mean marked it with "[[deprecated]]", so to discourage its usage and remove in a later major version release. 

If you are interested, will you create a pull request for it?

Thanks,
Bowen

**Comment by hugoetchegoyen** [comment]
Hi Bowen,

I think I suceeded. The changes are very small. You can use 'others' as when predicates or handlers now. I attach a file with the changes and the sample program. Function expr() is still available, I used it (unnecessarily) in expr(i+j). If you would like to remove it, I guess it can be moved to namespace impl.

Regards,
Hugo

[matchit2.txt](https://github.com/BowenFu/matchit.cpp/files/9991421/matchit2.txt)

**Comment by BowenFu** [comment]
@hugoetchegoyen looks good to me. And you can also define a helper toNullary function inside impl namespace and than you will only need one version of when / operator=.

Are you planning to create a pull request yourself or you want me to create one for you?
Please let me know if you meet any issues when creating a PR.
To create a PR, you need to fork the repo and commit the changes to your fork repo firstly and then create a PR from your fork repo to this repo.
You can find more info here. Hope this helps.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

Thanks,
Bowen

**Comment by hugoetchegoyen** [comment]
Hi Bowen,

Great! The universal references solved it. If you think it's OK now I'll create a pull request.

Regards,
Hugo

[matchit4.txt](https://github.com/BowenFu/matchit.cpp/files/10014187/matchit4.txt)

**Comment by hugoetchegoyen** [comment]
PS sorry for the mistake, I did use std::decay_t in toNullary. Sent you an outdated file.

**Comment by hugoetchegoyen** [comment]
This is the updated file.

[matchit4.txt](https://github.com/BowenFu/matchit.cpp/files/10015337/matchit4.txt)

**Comment by hugoetchegoyen** [comment]
I already forked your repository, commited my changes, built the targets and ran unittest without  errors, so it seems the changes don't break existing code. I'll create a pull request as soon as you agree.

**Comment by BowenFu** [comment]
LGTM. Feel free to create a pull request. We can continue our discussions there (if any).

And can you also add some unit tests to cover the new code paths?

**Comment by hugoetchegoyen** [comment]
Thank you very much Bowen. 
Best regards,
Hugo
