### ISSUE TITLE
Update documentation to clean up unnecessary usage of expr.

### ISSUE THREAD

**Issue by BowenFu** [BowenFu/matchit.cpp#96]
This is a follow up task of https://github.com/BowenFu/matchit.cpp/pull/95

**Comment by hugoetchegoyen** [comment]
Bowen, now that expr() has been removed, test/optexpr.cpp is meaningless and should be removed too.
Best regfards,
Hugo

**Comment by BowenFu** [comment]
Hi @hugoetchegoyen, "expr()" will be kept at least until next major release. So it is better to keep the tests.

Since documentation has been updated in #98, I'm going to close this issue.

**Comment by hugoetchegoyen** [comment]
Ok, but in that case I guess optexpr.cpp should not be cleaned up of unnecessary expr()s. As it is now, both test cases (no_expr and unnecessary_expr) are identical and expr() is not used at all.

**Comment by BowenFu** [comment]
> Ok, but in that case I guess optexpr.cpp should not be cleaned up of unnecessary expr()s. As it is now, both test cases (no_expr and unnecessary_expr) are identical and expr() is not used at all.

That should be a mistake. Will recover that file.

**Comment by BowenFu** [comment]
Will be fixed by https://github.com/BowenFu/matchit.cpp/pull/99
